title: "Krishna Life Lessons"
description: "Ancient wisdom for modern living"
author: "Yash Shah"

# GitHub Pages settings
url: "https://yashshah-dev.github.io"
baseurl: "/krishna-life-lesson"

# GitHub Pages will automatically use supported plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation menu
header_pages:
  - index.md
  - chapters/chapter1.md
  - chapters/chapter2.md

# Language settings
languages:
  en:
    name: "English"
  gu:
    name: "ગુજરાતી"

# Exclude files from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md